CC=gcc
CFLAGS=-I../../src/

detect_single_character_xor: detect_single_character_xor.c ../../src/hex.c ../../src/utils.c
	$(CC) -o detect_single_character_xor detect_single_character_xor.c ../../src/hex.c ../../src/utils.c
