CC=gcc
CFLAGS=-I../../src/

convert_hex_to_base64: convert_hex_to_base64.c ../../src/hex.c ../../src/base64.c
	$(CC) -o convert_hex_to_base64 convert_hex_to_base64.c ../../src/hex.c ../../src/base64.c
